### POST a signup for the service
POST http://localhost:28852/api/auth/signup
Content-Type: application/json
Accept: application/json

{
  "name": "Nick",
  "lastname": "Smith",
  "email": "nick.smith@acme.com",
  "password": "123456"
}

### POST a signup with malformed email
POST http://localhost:28852/api/auth/signup
Content-Type: application/json
Accept: application/json

{
  "name": "Nick",
  "lastname": "Smithy",
  "email": "nick.smith@acm.com",
  "password": "123456"
}